import Head from 'next/head'
import React from 'react'

export default function DecisionMaker() {
  return (
    <>
      <Head>
        <title>A Collection of Coolest Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <h1>Decision Maker</h1>
        </main>
    </>
  )
}
