import Head from 'next/head'
import Link from 'next/link'
import React from 'react'
import { List } from 'antd'

const myApps = [
  {
    'title': 'One Submit! No Regret!',
    'description': 'Having trouble making decisions? Don\'t worry! We will help you!',
    'link': '/decision-maker'
  },
  {
    'title': 'Become A Billionaire',
    'description': 'Are you a billionaire?',
    'link': '/billionaire'
  }
]

export default function Home() {
  return (
    <>
      <Head>
        <title>A Collection of Coolest Tools</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <List
            header={<h2>A Collection of Coolest Tools</h2>}
            dataSource={myApps}
            renderItem={(item) => (
              <List.Item>
                <List.Item.Meta
                  title={<Link href={item.link}>{item.title}</Link>}
                  description={item.description}
                />
              </List.Item>
            )}
          />
      </main>
    </>
  )
}
